language: java
sudo: required
dist: trusty
matrix:
   include:
      - jdk: oraclejdk7
        os: linux
        env: PROJ=artoolkitplus OS=linux-x86_64
      - jdk: oraclejdk7
        os: linux
        env: PROJ=caffe OS=linux-x86_64
      - jdk: oraclejdk7
        os: linux
        env: PROJ=chilitags OS=linux-x86_64
      - jdk: oraclejdk7
        os: linux
        env: PROJ=cuda OS=linux-x86_64

      - os: osx
        env: PROJ=artoolkitplus OS=macosx-x86_64
      - os: osx
        env: PROJ=caffe OS=macosx-x86_64
      - os: osx
        env: PROJ=chilitags OS=macosx-x86_64
      - os: osx
        env: PROJ=cuda OS=macosx-x86_64
before_install:
   - if [ "$TRAVIS_OS_NAME" == "osx" ]; then export JAVA_HOME=$(/usr/libexec/java_home); fi
install:
   - ./cppbuild.sh -platform $OS install $PROJ
script:
   - mvn install -Djavacpp.platform $OS -pl $PROJ
cache:
   directories:
      - $HOME/.m2
